export const styles = {
  container: (theme) => ({
    margin: '0 auto',
    padding: '2rem',
    backgroundColor: theme === 'light' ? '#ffffff' : '#1a1a1a',
    color: theme === 'light' ? '#000000' : '#ffffff',
    minHeight: '100vh',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  }),
  notesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    marginTop: '2rem',
    width: '100%',
    maxWidth: '800px',
  },
  noteItem: (theme) => ({
    backgroundColor: theme === 'light' ? '#f5f5f5' : '#2a2a2a',
    padding: '15px',
    marginBottom: '10px',
    borderRadius: '4px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.12)',
    position: 'relative',
    paddingRight: '80px',
  }),
  noteMetadata: (theme) => ({
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '0.5rem',
    fontSize: '0.875rem',
    color: theme === 'light' ? '#666' : '#999',
  }),
  deleteButton: {
    padding: '0.25rem 0.5rem',
    backgroundColor: '#ff4444',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    position: 'absolute',
    right: '15px',
    top: '15px',
  },
  themeToggle: {
    marginTop: '2rem',
    textAlign: 'center',
  },
  toggleButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#4444ff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContent: (theme) => ({
    backgroundColor: theme === 'light' ? '#fff' : '#333',
    padding: '20px',
    borderRadius: '8px',
    width: '90%',
    maxWidth: '500px',
  }),
  noteTextarea: {
    width: '100%',
    minHeight: '150px',
    margin: '10px 0',
    padding: '8px',
    borderRadius: '4px',
  },
  modalButtons: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  saveButton: {
    padding: '8px 16px',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  cancelButton: {
    padding: '8px 16px',
    backgroundColor: '#f44336',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  captureButton: {
    padding: '8px 16px',
    backgroundColor: '#2196F3',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    marginBottom: '20px',
  },
} 