export const styles = {
  container: (theme) => ({
    margin: '0 auto',
    padding: '2rem',
    backgroundColor: theme === 'light' ? '#ffffff' : '#1a1a1a',
    color: theme === 'light' ? '#000000' : '#ffffff',
    minHeight: '100vh',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
  }),
  notesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    marginTop: '2rem',
  },
  noteItem: (theme) => ({
    padding: '1rem',
    borderRadius: '8px',
    backgroundColor: theme === 'light' ? 'rgba(0, 0, 0, 0.05)' : 'rgba(255, 255, 255, 0.1)',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  }),
  noteMetadata: (theme) => ({
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '0.5rem',
    fontSize: '0.875rem',
    color: theme === 'light' ? '#666' : '#999',
  }),
  deleteButton: {
    padding: '0.25rem 0.5rem',
    backgroundColor: '#ff4444',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  themeToggle: {
    marginTop: '2rem',
    textAlign: 'center',
  },
  toggleButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#4444ff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },
} 